[package]
name = "imageworker"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
lapin = "4.11.0"
serde = "1.0.229"
tokio = { version = "1.53.1", features = ["full"] }
aws-config = { version = "1.1.7", features = ["default"] }
aws-sdk-s3 = "1.146.1"
serde_json = "1.0.151"
image = "0.25.10"